### ISSUE TITLE
Possible misspelling in db_server/README.md?

### ISSUE THREAD

**Issue by naltun** [gautamkrishnar/nothing-private#10]
In `db_server/README.md`, it says `Uses the PHP POD database access.` I think you meant `PHP PDO`, as in PHP Data Objects?

I may even rewrite this as `Uses the PHP PDO extension for database access.`

**Comment by gautamkrishnar** [comment]
@naltun yea thats what i mean... Feel free to make any changes... (y)

**Comment by naltun** [comment]
Made an update. Feel free to leave feedback.
