### ISSUE TITLE
Fingerprint can be defeated by changing browser size

### ISSUE THREAD

**Issue by r-a-y** [gautamkrishnar/nothing-private#102]
Just stumbled upon your project.

I wanted to try using the same browser session to see if my fingerprint can be detected. And I found that if you change your browser's window dimensions to something else and refresh the page, you will not be detected :)

**Comment by gautamkrishnar** [comment]
Yes it is possible. Also it can be overridden if you use a multi monitor setup especially if you have monitors with different resolution.
