### ISSUE TITLE
Browser with countermeasures: <Brave Private Window with Tor>

### ISSUE THREAD

**Issue by Frediflexta** [gautamkrishnar/nothing-private#117]
**Browser Name and website**
I am not entirely sure if this issue has been raised now. 

So I tried following the steps on my brave browser, but then when I was asked to open on a private browser window, I used a private window with Tor. I never got past this first page, It kept trying to verify if I am human.

![Screenshot 2020-09-10 at 01 06 54](https://user-images.githubusercontent.com/26186206/92666982-a1e75d00-f302-11ea-9398-9d03c1f8ff6e.png)

**Version** 
- Brave Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
**Operating System used**
- macOS
**Operating Systems supported**

**Notes**

**Comment by harshhh-dev** [comment]
Ah yeah. This happens with "new private window" too, not just "new private window with tor"

**Comment by gautamkrishnar** [comment]
Closing this in the favor of #127
