### ISSUE TITLE
Social sharing buttons

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/nothing-private#12]
Add an icon at the end of the webpage to share the webpage link to facebook, twitter and linkedin...
Please comment on this issue if you are interested.

**Comment by Logan1x** [comment]
Yes try to do if possible.

**Comment by tagawa** [comment]
Good idea. If it helps, I wrote about how to use social media buttons that don't track users here:
http://daniemon.com/blog/static-social-media-share-buttons/

The code's a bit old so some of the companies may have changed their behaviour.

**Comment by gautamkrishnar** [comment]
@tagawa yes it looks cool... :+1: 
@Logan1x You can use the code examples shared by daniel :smile:

**Comment by Logan1x** [comment]
Done..

**Comment by Logan1x** [comment]
When i checked on this social media buttons are working properly but when i run index.html it is not working. I don't know why 🤔

**Comment by gautamkrishnar** [comment]
@Logan1x i will fix it this evening... Don't worry...

**Comment by Logan1x** [comment]
ok
