### ISSUE TITLE
Browser with countermeasures: <Brave w/ private mode>

### ISSUE THREAD

**Issue by harshhhdev** [gautamkrishnar/nothing-private#127]
*Browser Name and website*

[Brave]

*Version*

1.16.75 Chromium: 86.0.4240.193 (Official Build) (64-bit)

*Operating System used*

Linux (Pop!_OS 20.10)

*Operating Systems supported*

Linux, Windows, OS X

*Notes*

I have tested this on mobile and on Desktop. It is able to track me on my phone (iPhone 6, iOS 12), though not on my laptop. There is an issue which shows that it is unable to track on Brave with Tor enabled, I want to note that this is with default private browsing, not Tor.

[Brave]: https://brave.com/

**Comment by gautamkrishnar** [comment]
@harshhhdev feel free to open up a PR for adding this one.
