### ISSUE TITLE
Does this website should say right name every time?Because i am getting wrong..

### ISSUE THREAD

**Issue by Logan1x** [gautamkrishnar/nothing-private#13]
![screenshot from 2017-07-06 12-09-37](https://user-images.githubusercontent.com/10944610/27898535-0c17c5f0-6244-11e7-88bb-2b7ccdae206e.png)
it is saying i am sankalp which is i am not.

**Comment by gautamkrishnar** [comment]
Someone else might had the same fingerprint... This is a rare case...

**Comment by Logan1x** [comment]
ok

**Comment by Logan1x** [comment]
yes and it does not giving me name to type.
