### ISSUE TITLE
Change the facebook share preview image

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/nothing-private#21]
Currently, when a user shares nothing private to Facebook, this icon is shown as preview:
![image](https://user-images.githubusercontent.com/8397274/28248487-e8fd0b58-6a62-11e7-91fa-37c1eb3e949d.png)
We need to modify the preview image and use http://www.nothingprivate.ml/private.jpg instead. :smile:

###  How to fix
1. Comment on this issue and claim it if you are interested.
2. Just edit [index.html](https://github.com/gautamkrishnar/nothing-private/blob/master/index.html) and add the following code to the `<head></head>` tag.
```
 <meta property="og:image" content="http://www.nothingprivate.ml/private.jpg" />
```
3. Open a pull request

**Comment by Logan1x** [comment]
I would like to work on that

**Comment by gautamkrishnar** [comment]
@Logan1x 
👍

**Comment by Logan1x** [comment]
@gautamkrishnar it is not visible to me now should i send pr?
