### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by brunomassa** [gautamkrishnar/nothing-private#23]
In fact is a god idea show that the user dont stay safe in private/incógnito mode. The website Works perfect but I have one sugestion.

For better explanation add a button that clear user data to possibility entering new data.

Something like that:
cleardata.php

```
<?php

header("Access-Control-Allow-Origin: *");
$location = "sqlite:".__DIR__."/safebrowsing.sqllite3";

if (isset($_GET['finger']))
{
    $dbh = new PDO($location) or die("cannot open the database"); 

    $stmt = $dbh->prepare("DELETE FROM browsertab WHERE fingerprint=?");
    $stmt->execute([$_GET['finger']]);
    $result = $stmt->fetch(); 

    $stmt->close();
}else{
//error while clear data
}
?>
```

**Comment by gautamkrishnar** [comment]
Yes... This looks good :+1:

**Comment by gautamkrishnar** [comment]
We need to display the clear data button only if the user is detected...

**Comment by gautamkrishnar** [comment]
Please open a PR if you are interested. I will add the front end stuffs later....

**Comment by brunomassa** [comment]
I'm working on it and when this is done i will make a pull request :D

**Comment by gautamkrishnar** [comment]
:+1: Please use the style of `see the magic` button for the `Forget Me` button, if you are working on the front end as well...
