### ISSUE TITLE
[Possible Bug] Shows name without entering anything

### ISSUE THREAD

**Issue by leovarmak** [gautamkrishnar/nothing-private#25]
Hey,

So I opened the site on my WP10 for the first time and it shows up as `You are Piyush`. I haven't entered any text before. I don't even know who is Piyush 

![whatsapp image 2017-07-22 at 09 19 33](https://user-images.githubusercontent.com/14135553/28488226-436af956-6ec3-11e7-8e28-7ad81c75adbb.jpeg)

**Comment by gautamkrishnar** [comment]
Yes it is a known bug of client.js library, It happens very rarely. We can't fix... Thanks for reporting... 👍
