### ISSUE TITLE
It's not perfect, but it's there...

### ISSUE THREAD

**Issue by Tilepaper** [gautamkrishnar/nothing-private#27]
I'm not going to leave what name I typed, but it took a couple of tries (without the forget me button!) with Google Chrome (no incognito required) to identify me. I used the same device (a Windows laptop) and accessed the site three times within five minutes. It finally work at the end.

Congrats. I am impressed with it, though.

![image](https://user-images.githubusercontent.com/25676806/30236371-0cc19c22-94e6-11e7-8bf4-8596ad7ad92f.png) (first try, no incognito)
![image](https://user-images.githubusercontent.com/25676806/30236394-97053736-94e6-11e7-9be6-4718b0aa21c3.png) (second try, incognito, and still not recognized...)
![image](https://user-images.githubusercontent.com/25676806/30236430-195bc3b2-94e7-11e7-99e6-43f6981f2163.png) (third time. recognized. Same incognito session.)

**Comment by Tilepaper** [comment]
It seems to depend on the browser, since I opened the website with Microsoft Edge and Internet Explorer (a few minutes I posted what's above) with no recognition. So, I'm interested: what method are you using to identify the same (?) ? Is it something in the browser itself, whichever one it may be? I've now tried it with different browsers and different names (§§§§§§ is my favourite!) and none of the names going to other browsers. It's the same physical device, all at the same time.

**Comment by gautamkrishnar** [comment]
The project uses Client.Js browser fingerprinting. To know more about clientJS visit: https://clientjs.org/.

## What is browser fingerprinting?
When you visit a website, you are allowing that site to access a lot of information about your computer's configuration. Combined, this information can create a kind of fingerprint — a signature that could be used to identify you and your computer. Some companies use this technology to try to identify individual computers. Fingerprinting is a technique, outlined in the research by Electronic Frontier Foundation, of anonymously identifying a web browser with accuracy of up to **94%**.

A browser is queried for its agent string, screen color depth, language, installed plugins with supported mime types, timezone offset and other capabilities, such as local storage and session storage. Then these values are passed through a hashing function to produce a fingerprint that gives weak guarantees of uniqueness.

Read more: https://github.com/Valve/fingerprintjs#what-is-fingerprinting
