### ISSUE TITLE
Failed to track in Firefox Quantum 57.0.4

### ISSUE THREAD

**Issue by CrisMen** [gautamkrishnar/nothing-private#37]
It does not work if I start the tracking in normal mode then switch to private mode: seems FF Quantum is working well!

**Comment by gautamkrishnar** [comment]
@CrisMen Happy to know that 😄  

They started some discussions earlier: 
* https://github.com/mozilla-mobile/focus-android/issues/900
* https://plus.google.com/+la%C3%A9rciohenriquedasilva/posts/UAZPhC7qrfi

**Comment by gautamkrishnar** [comment]
closing this one.... we will be adding a list of browsers that this tracking is not working to the readme soon
