### ISSUE TITLE
Add more web browsers after testing

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/nothing-private#38]
* Populate the list of secure web browsers that doesn't allows browser fingerprinting after visiting the www.nothingprivate.ml in them. If you are not able to fingerprint using that browser, add it to the list: https://github.com/gautamkrishnar/nothing-private/blob/master/Secure-Browsers.md
* Verify whether the browsers listed there are actually secure against fingerprinting.

**Comment by igniteeng000** [comment]
We also have to add list of unsecure browsers to show how many browsers we have tested, because most browsers are unsecure. I will be happy to list them

**Comment by gautamkrishnar** [comment]
@igniteeng000 i am not planning to add the list of browsers that supports this implementation because it may be too long list. Btw thanks for your suggestion 👍

**Comment by Aseged** [comment]
Hi, it is my first time working and contributing to open source, do you mind if I take a look? @gautamkrishnar

**Comment by gautamkrishnar** [comment]
@Aseged you are always welcome... Open a PR once you have done with it. Thanks 😄

**Comment by gautamkrishnar** [comment]
@tuscior yes you can. Thanks a lot for your interest

**Comment by memariyan** [comment]
firefox quantom tracking fingerprint too

**Comment by zcapshaw** [comment]
Hi @gautamkrishnar - In my testing I found that the browser Brave (https://brave.com/download/) does not allow fingerprinting as long as you use the "Private Tab with Tor" feature. I submitted a PR to the Secure Browsers list. Happy hacktoberfest :)

**Comment by gautamkrishnar** [comment]
Awesome @zcapshaw expecting more PRs... 😄

**Comment by WilliamNagel** [comment]
I am using Firefox 63.0.1 and when I open a private tab, [nothingprivate.ml]https://www.nothingprivate.ml/) does not know my name. What am I doing right (or wrong)?

**Comment by gautamkrishnar** [comment]
@WilliamNagel it sometimes wont work. Can you please check a similar issue for the explanation: https://github.com/gautamkrishnar/nothing-private/issues/27

**Comment by WilliamNagel** [comment]
I tried it again with another name and when I go to [www.nothingprivate.ml](www.nothingprivate.ml) in a private tab now it shows me the name from yesterday.

**Comment by Keerahere** [comment]
I have it in CM browser in android its not working
is cm-browser private tab is secure from browser fingerprint leaks?

**Comment by Keerahere** [comment]
No its not sorry that was the problem of server api

**Comment by antomor** [comment]
I can confirm, that with Firefox 70.0.1 on macOS, fingerprinting is successful, even by applying the config suggested in [notes](https://github.com/gautamkrishnar/nothing-private/blob/master/firefox_quantum_notes.md).

**Comment by monstorix** [comment]
> 
> 
> I can confirm, that with Firefox 70.0.1 on macOS, fingerprinting is successful, even by applying the config suggested in [notes](https://github.com/gautamkrishnar/nothing-private/blob/master/firefox_quantum_notes.md).

On Firefox Developer Edition(71.0a8) for Windows 10 x64 , the fingerprinting is blocked successfully after applying the configs.
![ff71](https://user-images.githubusercontent.com/9211781/68676171-4d901700-0551-11ea-916d-957271f9165f.png)

**Comment by pramodhrachuri** [comment]
Old Edge on Windows 10 takes forever to load but works as said in Chrome and Edge Beta.

![Screenshot (808)](https://user-images.githubusercontent.com/13718503/70375656-3cef7880-1926-11ea-8e3e-b72505d310eb.png)

**Comment by SeBarosanul** [comment]
@gautamkrishnar Brave Browser doesn't allow fingerprinting without the need to use the tor window.
I tested this on Windows 10 with stock Brave.

**Comment by gautamkrishnar** [comment]
@SeBarosanul thanks for reporting, tried locally looks like brave is blocking fingerprints even when using normal private browsing mode. Good to know that. Nothing private doesn't work on brave tor mode due to Cloudflare security policies. Can you open a PR to add brave to the list of the secure browsers?

**Comment by GuiAmPm** [comment]
Adding the Add-on "Font fingerprint defender" to Firefox 76 confused the tracker.

**Comment by apandada1** [comment]
Firefox 77 (in KDE Neon) successfully blocks the fingerprint. I am using ublock origin and DuckDuckGo Privacy Essentials. These extensions are probably not responsible because nothingprivate.ml used to work in Firefox 75 with the same extensions
