### ISSUE TITLE
Not working on Chrome Version 56.0.2924.87

### ISSUE THREAD

**Issue by inboxdarpan** [gautamkrishnar/nothing-private#5]
I tried it, though it couldn't reproduce name that I provided in normal browser.

**Comment by gautamkrishnar** [comment]
I will look into this...

**Comment by gautamkrishnar** [comment]
Just checked using the [browserstack](https://www.browserstack.com/) and its working fine for me:
![win10_chrome_56 0](https://cloud.githubusercontent.com/assets/8397274/23568038/deb417c0-007e-11e7-8075-cd3073904d73.jpg)
![win10_chrome_56 0 1](https://cloud.githubusercontent.com/assets/8397274/23568039/df8e4d6e-007e-11e7-8140-39b2bf77f097.jpg)

**Comment by gautamkrishnar** [comment]
@inboxdarpan Which operating system are you using? It may be the problem of your browser blocking flash. You must enable flash to make it work.

**Comment by inboxdarpan** [comment]
Yes it is working now. I did not even enable/disable flash or anything. But it is working now. Thanks.
