### ISSUE TITLE
Error on page: An API error occurred! Please try again. 

### ISSUE THREAD

**Issue by gurungrahul2** [gautamkrishnar/nothing-private#57]
https://www.nothingprivate.ml/ is not working it says:

Nothing Private is using free hosting (00Webhost) to host the APIs.
It doesn't guarantee 100% uptime. Sorry for the inconvenience caused.

**Comment by gautamkrishnar** [comment]
Hi @gurungrahul2 as message says, we are using 00Webhost. It is a free hosting service. It doesn't offers 100% Uptime. Please retry, it should be working now. If you are still experiencing the problem please export the network logs and attach it with the bug as har format (https://datameer.zendesk.com/hc/en-us/articles/204847860-How-to-Collect-the-Network-HAR-File-Logs-from-a-Developer-Tools-Session). Closing this for now.

**Comment by gurungrahul2** [comment]
@gautamkrishnar I was on college lab in the morning, but on my machine it is working fine.

**Comment by gautamkrishnar** [comment]
Awesome @gurungrahul2 It may be some network issue then.
