### ISSUE TITLE
stuck: `Loading... please wait...`

### ISSUE THREAD

**Issue by zaoqi** [gautamkrishnar/nothing-private#64]
**Describe the bug**

**To Reproduce**
1. use `Brave`
2. block script
3. block all Device recognition
4. https://www.nothingprivate.ml/

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Brave
 - Version 0.68.131

**Additional context**

**Comment by gautamkrishnar** [comment]
This website don't work without javascript enabled. Block script will block js. I am able to get it working correctly in brave:
<img width="1440" alt="Screenshot 2019-08-25 at 7 28 20 PM" src="https://user-images.githubusercontent.com/8397274/63651030-acbe6680-c76e-11e9-9cc0-7a1ae37e3a24.png">
