### ISSUE TITLE
Using Fingerint.js instead of Client.js for more accurate fingerprinting

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/nothing-private#87]
- [x] Use fingerprint.js
- [x] Optimise perfomance
- [x] Improve code style
- [x] Launch beta

This change is now live at https://5dd928dec0ff8700082b409d--preview-npvt.netlify.com/ for beta tests. Please comment on this PR if you encounter any issues.

**Comment by Tuanthai4444** [comment]
![chromewithbeta](https://user-images.githubusercontent.com/39924523/69463239-fd266f80-0d2f-11ea-851f-fe8c03a61226.jpg)

Beta not working for Google Chrome Version (Version 78.0.3904.108 64-bit) which works on nothingprivate.ml

**Comment by gautamkrishnar** [comment]
@Tuanthai4444 Thanks for testing

**Comment by gautamkrishnar** [comment]
@Tuanthai4444 is https://nothingprivate.ml/ working fine for you?

**Comment by Tuanthai4444** [comment]
@gautamkrishnar Yes it is, forgot to mention that

**Comment by gautamkrishnar** [comment]
@all-contributors please add @Tuanthai4444 for test
