### ISSUE TITLE
Clicking 'See the magic!' button multiple times reloads the page more than once.

### ISSUE THREAD

**Issue by HaridevVS** [gautamkrishnar/nothing-private#89]
When on the main page if you click 'See the magic button' multiple times fast enough, the page reloads twice and shows the message "You are test_name".

**To Reproduce**
1. Go to https://www.nothingprivate.ml/
2. Enter name and click on 'See the magic!' multiple times really fast.

**Expected behavior**
Only the "Now open a private browsing window or incognito window on your browser and visit www.nothingprivate.ml to see the magic...." page should load.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : 
      - Chrome 73.0.3683.86 
      - Firefox 70.0.1

I am submitting an issue for the first time. If there are any mistakes, please let me know.

**Comment by gautamkrishnar** [comment]
@HaridevVS Thanks for reporting the button should be disabled during the API Call hence preventing the multiple clicks.

**Comment by HaridevVS** [comment]
Chetta, I couldn't figure out how the API works to disable the button during call. I temporarily solved the problem by using a Boolean flag to check if renderNewTabPage() should be called or not. It is initialised to true and set to false if renderSubmit() is called. 

Is this okay ?

**Comment by gautamkrishnar** [comment]
Fixed in #91

**Comment by gautamkrishnar** [comment]
@all-contributors please add @HaridevVS for bug.
