### ISSUE TITLE
Firefox, waterfox fingerprinting protection not working (Not secure browsers!!!

### ISSUE THREAD

**Issue by nunbit** [gautamkrishnar/nothing-private#98]
I am reporting Firefox 73, Waterfox-current and Librewolf 72 as all insecure.

tested on linux with following:
default
with adons
fresh reset enabling only "resist fingerprinting"
different profiles don't matter either
in all cases I got remembered.

Thank you to all nothingprivate.ml devs for a great tool and amazing job.

**Comment by nunbit** [comment]
Just found out that ungoogled chromium (so chomium and chrome likely too) can prevent fingerprinting with these flags enabled:
Enable get*ClientRects() fingerprint deception
Enable Canvas::measureText() fingerprint deception 
Enable Canvas image data fingerprint deception

So you can add latest ungoogled chromium for arch into secure browsers section.
I am officially calling firefox data collecting conspiracy. No one can prove me wrong. No known config to prevent fingerprinting exists....wow.  I was fooled by firefox community for years and turns out firefox is worse than google. I am outraged disappointed and sick of firefox lies. Unistalling that spyware for good.

**Comment by gautamkrishnar** [comment]
This needs more testing. Please comment on the issue once you are done.

**Comment by hybridx** [comment]
Verified 
![Screenshot from 2020-02-24 12-02-05](https://user-images.githubusercontent.com/12994292/75132625-a600b400-56fd-11ea-88d6-f9f1a3816322.png)

**Comment by gautamkrishnar** [comment]
Thanks @hybridx

@all-contributors please add @hybridx for userTesting and @nunbit for bug

**Comment by gautamkrishnar** [comment]
@all-contrubutors add @nunbit for bug

**Comment by gautamkrishnar** [comment]
@all-contributors please add @nunbit for bug

**Comment by SpiCy0** [comment]
Tried to test this using the same tool, no results, web page the same every time I go, doesn't seem to remember.
I have RFP enabled, with CanvasBlocker, but as I didn't allow canvas extraction, CB was probably redundant. I also have a bunch of other extensions, as this is my default profile.
