### ISSUE TITLE
Secure browser: <Bromite v80>  <Ungoogled Chromium>

### ISSUE THREAD

**Issue by nunbit** [gautamkrishnar/nothing-private#99]
I can successfully report Bromite v80 on Android 10 resisting your fingerprinting, tried several time and I never got remembered after closing reopening app.

Ungoogled chromium can prevent fingerprinting with these flags enabled too:
Enable get*ClientRects() fingerprint deception
Enable Canvas::measureText() fingerprint deception
Enable Canvas image data fingerprint deception

**Comment by gautamkrishnar** [comment]
This one needs more testing.....

**Comment by gautamkrishnar** [comment]
@nunbit Can you please tell what version of APK you used to test this https://github.com/bromite/bromite/releases there are multiple APKs per release right?

**Comment by gautamkrishnar** [comment]
Verified Ungoogled chromium. Thanks for reporting @nunbit

**Comment by gautamkrishnar** [comment]
Verified bromite
